export const popularTopics: string[] = [
  "Mother's Day",
  'Summer',
  'Travel',
  'Italian food',
  'Wedding',
  'Neon sign',
  'Ocean',
  'Jungle',
  'Rain',
  'Chef',
  'Coral reef',
  'Workers',
  'Barbecue',
  'Berries',
  'Pastry',
  'Full moon',
  'Bouquet',
  'Wind',
  'Buddha',
  'Cinco de Mayo',
  'Night',
  'Nature',
  'Underwater',
  'Beautiful Zoom Backgrounds',
  'Orange Kiss',
  'Moving Backgrounds',
  'Sunset',
  'Mountains',
  'Cityscape',
  'Abstract',
  'Wildlife',
  'Street Photography',
  'Architecture',
  'Flowers',
  'Food',
  'Fitness',
  'Technology',
  'Business',
  'Travel Photography',
  'Portraits',
  'Black and White',
];
